version: "3.7"
services:
  devenv:
    user: vscode

    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "4000:4000"

    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - ../:/workspace:cached
      # Forwards the local Docker socket to the container.
      - ~/.config/gh:/home/vscode/.config/gh:cached
      - ~/.kube:/home/vscode/.kube:cached 

    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
